services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD : /run/secrets/db_root_password
      MYSQL_PASSWORD : /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    restart: on-failure
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - "wordpress"
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
      - .env
    restart: on-failure
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
    - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      WP_ADMIN_PASSWORD : /run/secrets/wp_admin_password
      WP_USER2_PASSWORD : /run/secrets/wp_user2_password
      MYSQL_PASSWORD : /run/secrets/db_password
    secrets:
      - db_password
      - wp_admin_password
      - wp_user2_password
    restart: on-failure
    depends_on:
      - "mariadb"
    expose:
      - "9000"
      
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gbussier/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gbussier/data/mariadb'

secrets:
   db_password:
     file: ../secrets/db_password.txt
   db_root_password:
     file: ../secrets/db_root_password.txt
   wp_admin_password:
     file: ../secrets/wp_admin_password.txt
   wp_user2_password:
     file: ../secrets/wp_user2_password.txt

networks:
  inception:
    driver: bridge